version: '2'

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitnami'

volumes:
  tomcat_data:
    driver: local
